"""Deterministic, seeded market simulator for GiffMeMoney.

This module turns the static :mod:`app.market.universe` seeds into reproducible
price histories, OHLCV candles, and the latent factor series that the quant
models regress against. Everything is derived from a stable hash of the symbol
(and a fixed constant for the *shared* factors), so the same symbol yields the
exact same history on every run, in every process — a hard requirement for
testable CAPM / Fama-French regressions.

Model
-----
A single, universe-wide :class:`MarketModel` generates four daily series that are
**shared by every asset**:

* ``mkt`` — the market factor's *total* daily return,
* ``smb`` — the small-minus-big (size) factor daily return,
* ``hml`` — the high-minus-low (value) factor daily return,
* ``rf``  — the daily risk-free rate (constant, from settings).

Each asset's daily return is then built from a 3-factor / single-index model::

    r_t = rf_d + market_beta * (mkt_t - rf_d)
              + smb_loading * SMB_t
              + hml_loading * HML_t
              + idiosyncratic noise

The market / SMB / HML / rf processes are seeded from a *fixed* constant
(``_MARKET_SEED``) so the factor history is identical for all assets — only the
idiosyncratic component is seeded per-symbol. Prices integrate the returns from
``base_price``. Intraday OHLC is synthesised around each close with small,
seeded noise.

All public functions are numerically defensive: degenerate parameters never
produce NaN/inf prices, and prices are floored to a tiny positive value.
"""

from __future__ import annotations

import hashlib
import math
import threading
import time
from functools import lru_cache
from typing import Dict, List

import numpy as np

from app.config import settings
from app.market.universe import AssetSeed, get_seed
from app.quant.returns import TRADING_DAYS

__all__ = [
    "seed_for",
    "MarketModel",
    "get_market_model",
    "generate_returns",
    "generate_prices",
    "daily_closes",
    "generate_candles",
    "latest_price",
    "market_closes",
    "market_returns",
    "factor_returns",
]

# Fixed seed for the *shared* market / SMB / HML / rf factor processes. Using a
# constant (rather than a per-symbol hash) guarantees every asset is driven by
# the SAME realised factor history, which is what makes the cross-sectional
# CAPM / Fama-French regressions meaningful.
_MARKET_SEED: int = 20240601

# Annual volatilities of the latent factors (decimals). The market premium and
# vols are plausible long-run values; SMB/HML are smaller, lower-vol spreads.
_MKT_ANNUAL_PREMIUM: float = 0.055   # E[mkt] - rf, annual
_MKT_ANNUAL_VOL: float = 0.16
_SMB_ANNUAL_MEAN: float = 0.015
_SMB_ANNUAL_VOL: float = 0.07
_HML_ANNUAL_MEAN: float = 0.010
_HML_ANNUAL_VOL: float = 0.08

# Smallest price we ever emit; keeps log/ratio math defined for cheap assets.
_PRICE_FLOOR: float = 1e-6

# Number of trailing daily closes generated by default. Driven by settings so a
# deployment can lengthen history without code changes.
_DEFAULT_DAYS: int = int(settings.history_days)


def seed_for(symbol: str) -> int:
    """Return a stable 32-bit RNG seed derived from a symbol.

    Formula:
        seed = int(sha256(symbol_upper).hexdigest(), 16) mod 2**32

    The same symbol always maps to the same seed across processes, so the
    idiosyncratic price path is reproducible.

    Args:
        symbol: Asset ticker (case-insensitive).

    Returns:
        An integer in ``[0, 2**32)`` suitable for ``numpy.random.default_rng``.
    """
    key = symbol.strip().upper().encode("utf-8")
    digest = hashlib.sha256(key).hexdigest()
    return int(digest, 16) % (2**32)


class MarketModel:
    """Generator and cache for the shared market / SMB / HML / rf factor series.

    The factor returns are drawn once (lazily) for a long horizon and cached;
    requests for ``days`` simply slice the **most recent** ``days`` observations
    so that, for any two horizons, the overlapping tail is identical. This makes
    the market history stable regardless of how much of it a caller asks for.

    The market factor's daily *total* return is::

        mkt_t = rf_d + premium_d + N(0, sigma_mkt_d)

    where ``rf_d`` and ``premium_d`` are the daily risk-free rate and equity
    premium. SMB and HML are zero-ish-mean spread processes.

    Attributes:
        rf_annual: Annual risk-free rate used to build the ``rf`` series.
        capacity: Length (in days) of the cached factor history.
    """

    def __init__(self, rf_annual: float, capacity: int) -> None:
        """Initialise the model and eagerly build the cached factor history.

        Args:
            rf_annual: Annual risk-free rate (decimal, e.g. ``0.04``).
            capacity: Number of daily observations to pre-generate. A floor of
                ``TRADING_DAYS`` (252) is enforced so even tiny configs have a
                full year of history.
        """
        self.rf_annual: float = float(rf_annual) if math.isfinite(rf_annual) else 0.0
        self.capacity: int = max(int(capacity), TRADING_DAYS)
        self._lock = threading.Lock()
        self._mkt: np.ndarray
        self._smb: np.ndarray
        self._hml: np.ndarray
        self._rf: np.ndarray
        self._build()

    def _build(self) -> None:
        """Draw and cache the full-length factor series from the fixed seed.

        Daily parameters are obtained from annual ones via the standard
        conventions: ``mean_d = annual / 252`` and
        ``sigma_d = annual_vol / sqrt(252)``.
        """
        rng = np.random.default_rng(_MARKET_SEED)
        n = self.capacity

        rf_d = self.rf_annual / TRADING_DAYS
        prem_d = _MKT_ANNUAL_PREMIUM / TRADING_DAYS
        mkt_sigma_d = _MKT_ANNUAL_VOL / math.sqrt(TRADING_DAYS)
        smb_mean_d = _SMB_ANNUAL_MEAN / TRADING_DAYS
        smb_sigma_d = _SMB_ANNUAL_VOL / math.sqrt(TRADING_DAYS)
        hml_mean_d = _HML_ANNUAL_MEAN / TRADING_DAYS
        hml_sigma_d = _HML_ANNUAL_VOL / math.sqrt(TRADING_DAYS)

        # Market total return = rf + premium + shock.
        mkt = rf_d + prem_d + rng.normal(0.0, mkt_sigma_d, size=n)
        smb = smb_mean_d + rng.normal(0.0, smb_sigma_d, size=n)
        hml = hml_mean_d + rng.normal(0.0, hml_sigma_d, size=n)
        rf = np.full(n, rf_d, dtype=np.float64)

        self._mkt = np.nan_to_num(mkt, nan=0.0, posinf=0.0, neginf=0.0)
        self._smb = np.nan_to_num(smb, nan=0.0, posinf=0.0, neginf=0.0)
        self._hml = np.nan_to_num(hml, nan=0.0, posinf=0.0, neginf=0.0)
        self._rf = rf

    def _tail(self, series: np.ndarray, days: int) -> np.ndarray:
        """Return the most-recent ``days`` observations of a cached series.

        If ``days`` exceeds the cached capacity the full series is returned
        (callers never need more than ``capacity`` in practice).

        Args:
            series: One of the cached factor arrays.
            days: Number of trailing observations requested.

        Returns:
            A copy of the last ``min(days, capacity)`` entries.
        """
        d = max(int(days), 1)
        if d >= series.size:
            return series.copy()
        return series[-d:].copy()

    def market(self, days: int) -> np.ndarray:
        """Return the shared market-factor daily total returns (last ``days``)."""
        return self._tail(self._mkt, days)

    def smb(self, days: int) -> np.ndarray:
        """Return the shared SMB-factor daily returns (last ``days``)."""
        return self._tail(self._smb, days)

    def hml(self, days: int) -> np.ndarray:
        """Return the shared HML-factor daily returns (last ``days``)."""
        return self._tail(self._hml, days)

    def rf(self, days: int) -> np.ndarray:
        """Return the shared daily risk-free series (last ``days``)."""
        return self._tail(self._rf, days)

    def factors(self, days: int) -> Dict[str, np.ndarray]:
        """Return all four shared factor series for the last ``days``.

        Returns:
            A dict with keys ``'mkt'``, ``'smb'``, ``'hml'``, ``'rf'`` mapping to
            equal-length ``float64`` arrays.
        """
        return {
            "mkt": self.market(days),
            "smb": self.smb(days),
            "hml": self.hml(days),
            "rf": self.rf(days),
        }

    def market_prices(self, days: int, base: float = 100.0) -> np.ndarray:
        """Integrate the market factor into a synthetic index price path.

        Formula:
            P_0 = base,  P_t = P_{t-1} * (1 + mkt_t)

        Args:
            days: Number of daily returns to integrate.
            base: Starting index level.

        Returns:
            A price array of length ``days + 1`` starting at ``base``.
        """
        rets = self.market(days)
        return _integrate_prices(rets, base)


# Module-level singleton, lazily constructed under a lock so concurrent
# WebSocket / request threads share one cached factor history.
_MODEL_LOCK = threading.Lock()
_MODEL: MarketModel | None = None


def get_market_model() -> MarketModel:
    """Return the process-wide :class:`MarketModel` singleton.

    The model is built once from :data:`app.config.settings` (risk-free rate and
    ``history_days``) and reused thereafter.

    Returns:
        The shared :class:`MarketModel`.
    """
    global _MODEL
    if _MODEL is None:
        with _MODEL_LOCK:
            if _MODEL is None:
                _MODEL = MarketModel(
                    rf_annual=settings.risk_free_rate,
                    capacity=_DEFAULT_DAYS,
                )
    return _MODEL


def _integrate_prices(returns: np.ndarray, base_price: float) -> np.ndarray:
    """Integrate a daily simple-return series into a price path.

    Formula:
        P_0 = base_price,  P_t = P_{t-1} * (1 + r_t), floored at ``_PRICE_FLOOR``.

    Args:
        returns: Daily simple returns (length ``n``).
        base_price: Strictly-positive starting price.

    Returns:
        A ``float64`` price array of length ``n + 1``. All entries finite and
        ``>= _PRICE_FLOOR``.
    """
    start = float(base_price) if math.isfinite(base_price) and base_price > 0 else 1.0
    r = np.asarray(returns, dtype=np.float64).ravel()
    r = np.nan_to_num(r, nan=0.0, posinf=0.0, neginf=0.0)
    # Clip per-step returns so a single shock can't drive price to <= -100%.
    r = np.clip(r, -0.95, 0.95)
    growth = np.concatenate(([1.0], np.cumprod(1.0 + r)))
    prices = start * growth
    prices = np.nan_to_num(prices, nan=start, posinf=start, neginf=_PRICE_FLOOR)
    return np.maximum(prices, _PRICE_FLOOR)


def generate_returns(seed: AssetSeed, days: int) -> np.ndarray:
    """Generate one asset's deterministic daily simple-return series.

    Formula (3-factor / single-index model):
        r_t = rf_d + beta * (mkt_t - rf_d)
                  + smb_load * SMB_t + hml_load * HML_t + idio_t

    where ``(mkt, smb, hml, rf)`` are the *shared* factor series from
    :class:`MarketModel` and ``idio_t ~ N(mu_idio_d, sigma_idio_d)`` is drawn
    from a per-symbol seeded RNG. The idiosyncratic mean is calibrated so the
    asset's realised drift matches its ``annual_drift`` after the factor
    contribution is accounted for.

    Args:
        seed: The asset's static :class:`AssetSeed`.
        days: Number of daily returns to generate (``>= 1``).

    Returns:
        A ``float64`` array of length ``days`` with finite daily returns.
    """
    n = max(int(days), 1)
    model = get_market_model()
    cap = model.capacity

    beta = float(seed.market_beta)
    smb_load = float(seed.smb_loading)
    hml_load = float(seed.hml_loading)
    idio_sigma_d = max(float(seed.idio_vol), 0.0) / math.sqrt(TRADING_DAYS)

    # Build the FULL-capacity return series first, then slice the requested tail.
    # Computing the drift calibration over the full, fixed window makes an asset's
    # returns (and thus its prices) invariant to how many days a caller requests:
    # the overlapping tail is always identical, exactly as for the factor series.
    mkt = model.market(cap)
    smb = model.smb(cap)
    hml = model.hml(cap)
    rf = model.rf(cap)

    # Systematic component (excludes idiosyncratic mean/noise).
    systematic = rf + beta * (mkt - rf) + smb_load * smb + hml_load * hml

    # Zero-mean idiosyncratic shocks over the full window (per-symbol seeded).
    rng = np.random.default_rng(seed_for(seed.symbol))
    idio_noise = rng.normal(0.0, idio_sigma_d, size=cap)

    # Calibrate a per-day drift constant so the simulated series' *log* drift
    # matches the seed's ``annual_drift`` for THIS realised factor path. Using
    # the realised means of the (fixed, shared) factor draws — rather than their
    # theoretical means — removes single-path sampling error, so beta-leveraged
    # assets recover their intended drift tightly and reproducibly.
    target_mu_d = float(seed.annual_drift) / TRADING_DAYS
    realised_systematic_mu = float(np.mean(systematic)) if cap > 0 else 0.0
    realised_noise_mu = float(np.mean(idio_noise)) if cap > 0 else 0.0
    # Half-variance correction converts the desired *log* drift target into the
    # arithmetic mean of the simple returns (E[1+r] = exp(mu + s^2/2)).
    total_var_d = float(np.var(systematic)) + idio_sigma_d**2
    arithmetic_target = target_mu_d + 0.5 * total_var_d
    drift_const = arithmetic_target - realised_systematic_mu - realised_noise_mu

    rets_full = systematic + idio_noise + drift_const
    rets = rets_full[-n:] if n < rets_full.size else rets_full
    return np.nan_to_num(rets, nan=0.0, posinf=0.0, neginf=0.0)


def generate_prices(seed: AssetSeed, days: int) -> np.ndarray:
    """Generate one asset's deterministic price path from its returns.

    Args:
        seed: The asset's static :class:`AssetSeed`.
        days: Number of daily returns (the path has ``days + 1`` prices).

    Returns:
        A ``float64`` price array of length ``days + 1`` starting at
        ``seed.base_price``. All entries finite and strictly positive.
    """
    rets = generate_returns(seed, days)
    return _integrate_prices(rets, seed.base_price)


@lru_cache(maxsize=256)
def _closes_cached(symbol: str, days: int) -> tuple:
    """Cached helper returning a symbol's close path as an immutable tuple.

    Caching keeps repeated analysis calls fast while preserving determinism.
    Returns a tuple (hashable / immutable) so ``lru_cache`` is safe; callers
    convert back to an array.

    Args:
        symbol: Asset ticker.
        days: Number of daily returns.

    Returns:
        A tuple of ``days + 1`` closing prices.
    """
    seed = get_seed(symbol)
    prices = generate_prices(seed, days)
    return tuple(float(p) for p in prices)


def daily_closes(symbol: str, days: int = _DEFAULT_DAYS) -> np.ndarray:
    """Return a symbol's deterministic daily closing prices.

    Args:
        symbol: Asset ticker (case-insensitive).
        days: Number of daily returns; the returned array has ``days + 1``
            closes (the extra is the ``base_price`` start point).

    Returns:
        A ``float64`` array of closing prices (length ``days + 1``).

    Raises:
        KeyError: If ``symbol`` is not in the universe.
    """
    return np.asarray(_closes_cached(symbol.strip().upper(), int(days)), dtype=np.float64)


def latest_price(symbol: str) -> float:
    """Return the most recent simulated close for a symbol.

    Args:
        symbol: Asset ticker (case-insensitive).

    Returns:
        The final close of the deterministic history as a float.

    Raises:
        KeyError: If ``symbol`` is not in the universe.
    """
    closes = daily_closes(symbol)
    return float(closes[-1])


def generate_candles(symbol: str, limit: int = 365) -> List[dict]:
    """Build deterministic daily OHLCV candles for a symbol.

    For each trailing daily close, synthetic intraday open/high/low values are
    derived around the close with small, *seeded* noise so the candles are
    realistic yet reproducible::

        open  = prev_close (jittered)
        high  = max(open, close) * (1 + |noise|)
        low   = min(open, close) * (1 - |noise|)
        vol   = base_volume * (1 + noise)

    Timestamps are spaced one calendar day apart ending at "now" (unix seconds),
    matching the :class:`app.schemas.Candle` DTO (``t`` in seconds).

    Args:
        symbol: Asset ticker (case-insensitive).
        limit: Maximum number of candles to return (the most recent ones).

    Returns:
        A list of dicts ``{'t','o','h','l','c','v'}`` ordered oldest → newest.
        ``t`` is unix **seconds**, OHLC are floats, ``v`` is a float volume.

    Raises:
        KeyError: If ``symbol`` is not in the universe.
    """
    sym = symbol.strip().upper()
    seed = get_seed(sym)
    n = max(int(limit), 1)

    closes = daily_closes(sym)
    if closes.size == 0:
        return []
    # Take the last n+1 closes so we have a previous close for each candle.
    window = closes[-(n + 1):] if closes.size > n else closes
    # A separate RNG stream (offset seed) drives intraday noise so it is stable
    # but independent from the return path's idiosyncratic draws.
    rng = np.random.default_rng((seed_for(sym) + 777) % (2**32))

    # Base 24h volume scaled to a per-candle figure.
    base_vol = float(seed.volume24h) if math.isfinite(seed.volume24h) else 0.0
    base_vol = max(base_vol, 0.0)

    now_s = int(time.time())
    day_s = 86400

    candles: List[dict] = []
    count = window.size - 1 if window.size > 1 else window.size
    # Align timestamps so the newest candle is "today".
    for i in range(1, window.size) if window.size > 1 else range(window.size):
        prev_close = float(window[i - 1]) if window.size > 1 else float(window[0])
        close = float(window[i]) if window.size > 1 else float(window[0])

        # Open gaps slightly from the previous close.
        gap = float(rng.normal(0.0, 0.004))
        open_ = prev_close * (1.0 + gap)

        hi_noise = abs(float(rng.normal(0.0, 0.006)))
        lo_noise = abs(float(rng.normal(0.0, 0.006)))
        hi = max(open_, close) * (1.0 + hi_noise)
        lo = min(open_, close) * (1.0 - lo_noise)
        # Guarantee a well-ordered candle.
        hi = max(hi, open_, close)
        lo = min(lo, open_, close)
        lo = max(lo, _PRICE_FLOOR)

        vol_noise = float(rng.normal(0.0, 0.25))
        vol = base_vol * max(0.1, 1.0 + vol_noise)

        steps_from_now = count - len(candles) - 1
        t = now_s - steps_from_now * day_s

        candles.append(
            {
                "t": int(t),
                "o": round(float(open_), 6),
                "h": round(float(hi), 6),
                "l": round(float(lo), 6),
                "c": round(float(close), 6),
                "v": round(float(vol), 2),
            }
        )
    return candles


def market_closes(days: int) -> np.ndarray:
    """Return the shared synthetic market-index closing prices.

    Args:
        days: Number of daily returns; result length is ``days + 1``.

    Returns:
        A ``float64`` array of index levels (starts at 100.0).
    """
    return get_market_model().market_prices(int(days), base=100.0)


def market_returns(days: int) -> np.ndarray:
    """Return the shared market-factor daily total returns.

    Args:
        days: Number of trailing daily returns.

    Returns:
        A ``float64`` array of length ``days``.
    """
    return get_market_model().market(int(days))


def factor_returns(days: int) -> Dict[str, np.ndarray]:
    """Return the shared factor daily-return series for ``days``.

    Args:
        days: Number of trailing daily returns.

    Returns:
        A dict ``{'mkt','smb','hml','rf'}`` of equal-length ``float64`` arrays.
    """
    return get_market_model().factors(int(days))
